### ISSUE TITLE
Issue in Source Field Not Mapped and Form Save Action Not Mapped

### ISSUE THREAD

**Issue by rajklj** [afaniuolo/WFFM-Conversion-Tool#18]
**Describe the bug**
in analysis report , I am seeing below messages;
**Source Field Not Mapped** --Check Actions,Form Alignment,Submit Button position,Is Ajax Mvc Form,Form Type,Submit Button type,Submit Button size
**Form Save Action Not Mapped** -- Save Actions

**Sitecore Platform Details**
* Source Sitecore Version: 8.1 update 3
* WFFM Module Version: 8.1.rev. 160523
* Destination Sitecore Version: 9.3
* Forms Data Provider (sql / mongodb):  sql

**Additional information**
Please let me know how would i map these fields

**Comment by afaniuolo** [comment]
Hi @rajklj ,

This section of the module documentation explains how to map custom fields or custom save actions:
https://github.com/afaniuolo/WFFM-Conversion-Tool#how-to-expand-the-wffm-conversion-tool-to-convert-custom-entities

If you have a concrete example of your custom field or your custom save action, I can help you to setup an example.
