### ISSUE TITLE
destFields parameter not applied to destination field

### ISSUE THREAD

**Issue by ahiyalala** [afaniuolo/WFFM-Conversion-Tool#20]
**Describe the bug**
`Section` item has a `Parameters` field with values `<CssClass>insert-css-here</CssClass>`, but these were not applied to the converted CssClass field in Sitecore Forms.

**Sitecore Platform Details**
* Source Sitecore Version: 9.0.2
* WFFM Module Version: 9.0 rev. 180503
* Destination Sitecore Version: 9.0.2
* Forms Data Provider (sql / mongodb): sql

**Additional information**
The Section metadata is unchanged:
```
"convertedFields": [
            {
                "fieldConverter": "",
                "sourceFieldId": "{821724F3-30BB-4152-A770-88BC43AC175A}", // Title
                "destFieldId": ""
            },
            {
                "fieldConverter": "",
                "sourceFieldId": "{358E7AA0-E3E6-4EF6-92DF-EC1301737B50}", // Parameters
                "destFields": [
                    {
                        "sourceElementName": "CssClass",
                        "destFieldId": "{7ABAA3F6-6EC0-4B65-A463-7919BFAE55AA}", // Css Class
                        "fieldConverter": ""
                    },
                    {
                        "sourceElementName": "ShowLegend",
                        "destFieldId": "",
                        "fieldConverter": ""
                    }
                ]
            },
            {
                "fieldConverter": "",
                "sourceFieldId": "{26CDC7C2-5307-4591-A7F9-5C034A05630A}", // Localized Parameters
                "destFields": [
                    {
                        "sourceElementName": "Information",
                        "destFieldId": "",
                        "fieldConverter": ""
                    }
                ]
            }
        ]
```

**Comment by afaniuolo** [comment]
Hi @ahiyalala,

Thank you for reporting this bug. I am able to reproduce it and I will work on fixing it as soon as possible.

I will let you know when it is fixed.

Thanks!
Alessandro

**Comment by afaniuolo** [comment]
Hi @ahiyalala,

The issue was caused by a duplicate mapping in the Section metadata file. In this commit you can see the lines that need to be deleted in the Section.json template metadata file:

https://github.com/afaniuolo/WFFM-Conversion-Tool/commit/fcecfdc76f2ac04484a7e187f11fc59147bfcd75

I will release an updated version of the tool in the next few days.

Thanks,
Alessandro

**Comment by ahiyalala** [comment]
Deleting that portion on the file worked! Thanks.
