### ISSUE TITLE
Introduction and Footer render as plain text

### ISSUE THREAD

**Issue by ahiyalala** [afaniuolo/WFFM-Conversion-Tool#21]
**Version 1.2.x**

I noticed that the Footer and Introduction of the WFFM form is converted into Text in Sitecore Forms. Given that the WFFM fields are Rich-text fields and the SF Text element is a multi-line text, the value of the WFFM field is not rendered properly. I have already installed the Sitecore Extensions, and I'm trying to locate the Metadata file where this is mapped so I can change it to SE's Raw HTML field.

**Comment by afaniuolo** [comment]
Hi @ahiyalala ,

I didn't want the tool to have a strong dependency with the Sitecore Forms Extensions module or any other modules.

If you want to implement this custom conversion behavior, you will not be able to achieve it just with the metadata field mapping, but you will need to modify these two methods of the FormAppearanceConverter class in the tool's source code with your custom mapping logic:

- [ConvertIntroduction](https://github.com/afaniuolo/WFFM-Conversion-Tool/blob/main/src/WFFM.ConversionTool.Library/Converters/FormAppearanceConverter.cs#L69)
- [ConvertFooter](https://github.com/afaniuolo/WFFM-Conversion-Tool/blob/main/src/WFFM.ConversionTool.Library/Converters/FormAppearanceConverter.cs#L99)

Good luck!
