### ISSUE TITLE
Duplicate items for multi-language dropdown list

### ISSUE THREAD

**Issue by ahiyalala** [afaniuolo/WFFM-Conversion-Tool#23]
**Describe the bug**
Dropdown options are duplicated if WFFM drop list is multilanguage

**Sitecore Platform Details**
* Source Sitecore Version: 9.0.2
* WFFM Module Version: 9.0.2
* Destination Sitecore Version: 9.0.2
* Forms Data Provider (sql / mongodb): sql

**Additional information**
A multi-language list-type field generates duplicate fields. While this is understandable given the fact that WFFM stores the options of list-type fields under the `Localized Parameters` field, the converter creates an item for each option with a version for each available language. Meaning the items created from the Localized Parameter's English version has a version for English and German, likewise for German creating a version for English and German. Where we would have expect each item from an English Localized Parameter to only have English version, and German to have German-versioned items so that we can use Enforce Version Presence for these forms.

![image](https://user-images.githubusercontent.com/14295998/96872297-fbdf5480-1462-11eb-9894-c675c11b377c.png)

**Comment by ahiyalala** [comment]
@afaniuolo added more description based on my further analysis on the issue.

**Comment by afaniuolo** [comment]
Hi @ahiyalala , are you using the latest version of the conversion tool? This seems very similar to issue #17 that was resolved in version 1.3.1 (for SC 9.3+) and version 1.2.1 (for earlier SC versions).

**Comment by ahiyalala** [comment]
I'm using version 1.2.1, I've read #17 and it's pertaining to values stored in the `Parameters` field, not on `Localized Parameter` perhaps that could've caused a difference?

**Comment by afaniuolo** [comment]
@ahiyalala It is possible. Can you please provide the raw value of one of the Localized Parameter fields that I can use to reproduce the issue?

**Comment by ahiyalala** [comment]
`Localized Parameter` value:
```
<SelectedValue></SelectedValue><Items>%3cquery+t%3d%22default%22+sov%3d%22true%22%3e%3cvalue%3eImmediatamente%3c%2fvalue%3e%3c%2fquery%3e%3cquery+t%3d%22default%22+sov%3d%22true%22%3e%3cvalue%3e1+mes%3c%2fvalue%3e%3c%2fquery%3e%3cquery+t%3d%22default%22+sov%3d%22true%22%3e%3cvalue%3e3+meses%3c%2fvalue%3e%3c%2fquery%3e</Items>
```
`Field Link` is `List Box`

**Comment by ahiyalala** [comment]
Also noticed on Line 31 of  `DatasourceConverter.cs` you have declared a variable `language` but I think it was was not used.

**Comment by afaniuolo** [comment]
@ahiyalala , thank you for the details. I will review it later tonight.

**Comment by afaniuolo** [comment]
Hi @ahiyalala , I implemented a fix for this issue and it is currently committed in the **v1.2.2** branch (compatible with the version of the tool that you are using). With this fix, multi-language list items that have the same value will be converted in a single multi-language list item with the same value, instead of having separate items (one for each language).

Please try it and let me know if it works as expected now. If it works, I will create a new official release of the tool. Thanks!

**Comment by ahiyalala** [comment]
Hi, thank you for your response! The results were better than expected, duplicate items have been prevented by the change. Even our German forms have been properly merged with its English counterpart.

**Comment by afaniuolo** [comment]
@ahiyalala I am glad that this issue is fixed now. Thank you again for reporting it. I will release an official release with this fix soon.
